// Generated by GAS WebApp Builder | Created by @Rafa Putra

function doGet(e) {
  var template = HtmlService.createTemplateFromFile('Index');
  template.runtimeMode = 'production';

  return template
    .evaluate()
    .setTitle('StrukListrik Pro')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

function setupDatabase() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  
  // Sheet Pelanggan
  var sheetPelanggan = ss.getSheetByName('Pelanggan');
  if (!sheetPelanggan) {
    sheetPelanggan = ss.insertSheet('Pelanggan');
    sheetPelanggan.appendRow(['ID', 'No Pelanggan', 'Nama', 'Tarif_Daya']);
    sheetPelanggan.setFrozenRows(1);
    sheetPelanggan.getRange("1:1").setFontWeight("bold");
  }
  
  // Sheet Pengaturan
  var sheetPengaturan = ss.getSheetByName('Pengaturan');
  if (!sheetPengaturan) {
    sheetPengaturan = ss.insertSheet('Pengaturan');
    sheetPengaturan.appendRow(['Kunci', 'Nilai']);
    sheetPengaturan.appendRow(['biayaAdmin', '2500']);
    sheetPengaturan.setFrozenRows(1);
    sheetPengaturan.getRange("1:1").setFontWeight("bold");
  }

  // Sheet Transaksi
  var sheetTransaksi = ss.getSheetByName('Transaksi');
  if (!sheetTransaksi) {
    sheetTransaksi = ss.insertSheet('Transaksi');
    sheetTransaksi.appendRow([
      'ID Transaksi', 'Tanggal', 'No Pelanggan', 'Nama', 
      'Tarif Daya', 'Periode', 'Stand Meter', 
      'Rp Tagihan PLN', 'Biaya Admin', 'Total Tagihan'
    ]);
    sheetTransaksi.setFrozenRows(1);
    sheetTransaksi.getRange("1:1").setFontWeight("bold");
  }

  return "Setup Database berhasil dilakukan. Silakan deploy aplikasi Anda.";
}

function generateId(prefix) {
  return prefix + '-' + new Date().getTime().toString(36).toUpperCase() + Math.floor(Math.random() * 1000);
}

// ==========================================
// API GET DATA
// ==========================================

function getAppData() {
  try {
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    
    // 1. Ambil Data Pelanggan
    var sheetPel = ss.getSheetByName('Pelanggan');
    var pelData = [];
    if (sheetPel) {
      var pelRows = sheetPel.getDataRange().getValues();
      for (var i = 1; i < pelRows.length; i++) {
        if(pelRows[i][0]) {
          pelData.push({
            id: pelRows[i][0],
            no: pelRows[i][1].toString(),
            nama: pelRows[i][2].toString(),
            tarif: pelRows[i][3].toString()
          });
        }
      }
    }

    // 2. Ambil Data Pengaturan
    var sheetPeng = ss.getSheetByName('Pengaturan');
    var pengData = { biayaAdmin: 2500 };
    if (sheetPeng) {
      var pengRows = sheetPeng.getDataRange().getValues();
      for (var j = 1; j < pengRows.length; j++) {
        if (pengRows[j][0] === 'biayaAdmin') {
          pengData.biayaAdmin = parseFloat(pengRows[j][1]) || 2500;
        }
      }
    }

    // 3. Ambil Data Transaksi (Batasi 100 baris terakhir dari bawah agar web tetap cepat)
    var sheetTrx = ss.getSheetByName('Transaksi');
    var trxData = [];
    if (sheetTrx) {
      var trxRows = sheetTrx.getDataRange().getValues();
      // Reverse loop (dari baris paling bawah ke atas)
      for (var k = trxRows.length - 1; k >= 1 && trxData.length < 100; k--) {
        if(trxRows[k][0]) {
          trxData.push({
            id: trxRows[k][0],
            tanggal: (trxRows[k][1] instanceof Date) ? trxRows[k][1].toISOString() : String(trxRows[k][1]),
            nopel: trxRows[k][2].toString(),
            nama: trxRows[k][3].toString(),
            tarif: trxRows[k][4].toString(),
            periode: trxRows[k][5].toString(),
            stand: trxRows[k][6].toString(),
            tagihanPLN: parseFloat(trxRows[k][7]) || 0,
            admin: parseFloat(trxRows[k][8]) || 0,
            total: parseFloat(trxRows[k][9]) || 0
          });
        }
      }
    }

    return { success: true, data: { pelanggan: pelData, pengaturan: pengData, transaksi: trxData } };
  } catch(e) {
    return { success: false, message: e.toString() };
  }
}

// ==========================================
// API PELANGGAN
// ==========================================

function savePelanggan(pData) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = ss.getSheetByName('Pelanggan');
    
    // Sanitasi input
    var pNo = (pData.no || '').toString().trim();
    var pNama = (pData.nama || '').toString().trim();
    var pTarif = (pData.tarif || '').toString().trim().toUpperCase();

    if (!pNo || !pNama) {
      return { success: false, message: 'Nomor Pelanggan dan Nama tidak boleh kosong.' };
    }

    if (pData.id && !pData.id.startsWith('temp-')) {
      // Logic untuk Edit
      var data = sheet.getDataRange().getValues();
      for (var i = 1; i < data.length; i++) {
        if (data[i][0] === pData.id) {
          sheet.getRange(i + 1, 2, 1, 3).setValues([[pNo, pNama, pTarif]]);
          pData.no = pNo; pData.nama = pNama; pData.tarif = pTarif;
          return { success: true, data: pData };
        }
      }
      return { success: false, message: 'Data pelanggan tidak ditemukan.' };
    } else {
      // Logic untuk Buat Baru
      pData.id = generateId('PLG');
      sheet.appendRow([pData.id, pNo, pNama, pTarif]);
      return { success: true, data: pData };
    }
  } catch(e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

function deletePelanggan(id) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Pelanggan');
    var data = sheet.getDataRange().getValues();
    
    for (var i = 1; i < data.length; i++) {
      if (data[i][0] === id) {
        sheet.deleteRow(i + 1);
        return { success: true };
      }
    }
    return { success: false, message: 'Data tidak ditemukan.' };
  } catch(e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

// ==========================================
// API PENGATURAN
// ==========================================

function savePengaturan(data) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Pengaturan');
    var rows = sheet.getDataRange().getValues();
    var found = false;

    var targetAdmin = parseFloat(data.biayaAdmin) || 0;

    for (var i = 1; i < rows.length; i++) {
      if (rows[i][0] === 'biayaAdmin') {
        sheet.getRange(i + 1, 2).setValue(targetAdmin);
        found = true;
        break;
      }
    }

    if (!found) {
      sheet.appendRow(['biayaAdmin', targetAdmin]);
    }

    return { success: true };
  } catch(e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

// ==========================================
// API TRANSAKSI
// ==========================================

function saveTransaksi(trx) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Transaksi');
    
    var newId = generateId('TRX');
    var timestamp = new Date();
    
    var rowData = [
      newId,
      timestamp,
      trx.nopel.toString().trim(),
      trx.nama.toString().trim(),
      trx.tarif.toString().trim(),
      trx.periode.toString().trim().toUpperCase(),
      trx.stand.toString().trim(),
      parseFloat(trx.tagihanPLN) || 0,
      parseFloat(trx.admin) || 0,
      parseFloat(trx.total) || 0
    ];

    sheet.appendRow(rowData);
    
    // Siapkan object untuk dikembalikan dan di-render di tabel Riwayat Frontend
    trx.id = newId;
    trx.tanggal = timestamp.toISOString();
    
    return { success: true, data: trx };
  } catch(e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}
