// Generated by GAS WebApp Builder | Created by @farhanalfaizi

function doGet(e) {
  var template = HtmlService.createTemplateFromFile('Index');
  
  // Penanda mutlak mode production (jangan diubah)
  template.runtimeMode = 'production';

  return template
    .evaluate()
    .setTitle('StrukListrik Pro')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

// ==========================================
// SETUP DATABASE
// ==========================================
function setupDatabase() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  
  // 1. Sheet Pelanggan
  var sheetPelanggan = ss.getSheetByName('Pelanggan');
  if (!sheetPelanggan) {
    sheetPelanggan = ss.insertSheet('Pelanggan');
    sheetPelanggan.appendRow(['ID', 'No Pelanggan', 'Nama', 'Tarif_Daya']);
    sheetPelanggan.setFrozenRows(1);
    sheetPelanggan.getRange("1:1").setFontWeight("bold");
  }
  
  // 2. Sheet Pengaturan
  var sheetPengaturan = ss.getSheetByName('Pengaturan');
  if (!sheetPengaturan) {
    sheetPengaturan = ss.insertSheet('Pengaturan');
    sheetPengaturan.appendRow(['Kunci', 'Nilai']);
    sheetPengaturan.appendRow(['biayaAdmin', '2500']);
    sheetPengaturan.setFrozenRows(1);
    sheetPengaturan.getRange("1:1").setFontWeight("bold");
  }

  // 3. Sheet Transaksi
  var sheetTransaksi = ss.getSheetByName('Transaksi');
  if (!sheetTransaksi) {
    sheetTransaksi = ss.insertSheet('Transaksi');
    sheetTransaksi.appendRow([
      'ID Transaksi', 'Tanggal', 'No Pelanggan', 'Nama', 
      'Tarif Daya', 'Periode', 'Stand Meter', 
      'Rp Tagihan PLN', 'Biaya Admin', 'Total Tagihan'
    ]);
    sheetTransaksi.setFrozenRows(1);
    sheetTransaksi.getRange("1:1").setFontWeight("bold");
  }

  // 4. Sheet AuditLog (Sistem Keamanan Log)
  var sheetAudit = ss.getSheetByName('AuditLog');
  if (!sheetAudit) {
    sheetAudit = ss.insertSheet('AuditLog');
    sheetAudit.appendRow(['Timestamp', 'User Email', 'Action', 'Detail']);
    sheetAudit.setFrozenRows(1);
    sheetAudit.getRange("1:1").setFontWeight("bold");
  }

  return "Setup Database berhasil dilakukan. Semua Sheet (Pelanggan, Pengaturan, Transaksi, AuditLog) sudah siap.";
}

// ==========================================
// UTILITIES
// ==========================================
function generateId(prefix) {
  return prefix + '-' + new Date().getTime().toString(36).toUpperCase() + Math.floor(Math.random() * 1000);
}

function logAction(action, detail) {
  try {
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('AuditLog');
    if (sheet) {
      var user = Session.getActiveUser().getEmail() || 'Anonymous';
      sheet.appendRow([new Date(), user, action, detail]);
    }
  } catch (e) {
    // Fail-safe: jika log gagal, jangan putus eksekusi utama
  }
}

// ==========================================
// API GET DATA
// ==========================================
function getAppData() {
  try {
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    
    // Get Data Pelanggan
    var sheetPel = ss.getSheetByName('Pelanggan');
    var pelData = [];
    if (sheetPel) {
      var pelRows = sheetPel.getDataRange().getValues();
      for (var i = 1; i < pelRows.length; i++) {
        if(pelRows[i][0]) {
          pelData.push({
            id: String(pelRows[i][0]),
            no: String(pelRows[i][1]),
            nama: String(pelRows[i][2]),
            tarif: String(pelRows[i][3])
          });
        }
      }
    }

    // Get Data Pengaturan
    var sheetPeng = ss.getSheetByName('Pengaturan');
    var pengData = { biayaAdmin: 2500 };
    if (sheetPeng) {
      var pengRows = sheetPeng.getDataRange().getValues();
      for (var j = 1; j < pengRows.length; j++) {
        if (pengRows[j][0] === 'biayaAdmin') {
          pengData.biayaAdmin = parseFloat(pengRows[j][1]) || 2500;
        }
      }
    }

    // Get Data Transaksi (Batasi 100 row terakhir agar load cepat)
    var sheetTrx = ss.getSheetByName('Transaksi');
    var trxData = [];
    if (sheetTrx) {
      var trxRows = sheetTrx.getDataRange().getValues();
      // Loop dari paling bawah agar transaksi terbaru di urutan teratas
      for (var k = trxRows.length - 1; k >= 1 && trxData.length < 100; k--) {
        if(trxRows[k][0]) {
          trxData.push({
            id: String(trxRows[k][0]),
            tanggal: (trxRows[k][1] instanceof Date) ? trxRows[k][1].toISOString() : String(trxRows[k][1]),
            nopel: String(trxRows[k][2]),
            nama: String(trxRows[k][3]),
            tarif: String(trxRows[k][4]),
            periode: String(trxRows[k][5]),
            stand: String(trxRows[k][6]),
            tagihanPLN: parseFloat(trxRows[k][7]) || 0,
            admin: parseFloat(trxRows[k][8]) || 0,
            total: parseFloat(trxRows[k][9]) || 0
          });
        }
      }
    }

    return { success: true, data: { pelanggan: pelData, pengaturan: pengData, transaksi: trxData } };
  } catch(e) {
    return { success: false, message: "Terjadi kesalahan sistem saat memuat data: " + e.message };
  }
}


// ==========================================
// API CRUD PELANGGAN
// ==========================================
function savePelanggan(pData) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    var ss = SpreadsheetApp.getActiveSpreadsheet();
    var sheet = ss.getSheetByName('Pelanggan');
    
    // Sanitasi input
    var pNo = String(pData.no || '').trim();
    var pNama = String(pData.nama || '').trim();
    var pTarif = String(pData.tarif || '').trim().toUpperCase();

    if (!pNo || !pNama) {
      return { success: false, message: 'Nomor Pelanggan dan Nama tidak boleh kosong.' };
    }

    // Proses UPDATE
    if (pData.id && !pData.id.startsWith('temp-')) {
      var data = sheet.getDataRange().getValues();
      for (var i = 1; i < data.length; i++) {
        if (String(data[i][0]) === pData.id) {
          sheet.getRange(i + 1, 2, 1, 3).setValues([[pNo, pNama, pTarif]]);
          logAction('UPDATE_PELANGGAN', 'Perbarui pelanggan ID: ' + pData.id);
          return { success: true, data: pData };
        }
      }
      return { success: false, message: 'Data pelanggan tidak ditemukan di server.' };
    } 
    // Proses CREATE
    else {
      pData.id = generateId('PLG');
      sheet.appendRow([pData.id, pNo, pNama, pTarif]);
      logAction('CREATE_PELANGGAN', 'Tambah pelanggan baru: ' + pNo);
      return { success: true, data: pData };
    }
  } catch(e) {
    return { success: false, message: 'Kesalahan sistem: ' + e.message };
  } finally {
    lock.releaseLock();
  }
}

function deletePelanggan(id) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Pelanggan');
    var data = sheet.getDataRange().getValues();
    
    for (var i = 1; i < data.length; i++) {
      if (String(data[i][0]) === id) {
        sheet.deleteRow(i + 1);
        logAction('DELETE_PELANGGAN', 'Menghapus pelanggan ID: ' + id);
        return { success: true };
      }
    }
    return { success: false, message: 'Data pelanggan tidak ditemukan di server.' };
  } catch(e) {
    return { success: false, message: 'Kesalahan sistem: ' + e.message };
  } finally {
    lock.releaseLock();
  }
}


// ==========================================
// API CRUD PENGATURAN
// ==========================================
function savePengaturan(data) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Pengaturan');
    var rows = sheet.getDataRange().getValues();
    var found = false;

    var targetAdmin = parseFloat(data.biayaAdmin) || 0;

    for (var i = 1; i < rows.length; i++) {
      if (rows[i][0] === 'biayaAdmin') {
        sheet.getRange(i + 1, 2).setValue(targetAdmin);
        found = true;
        break;
      }
    }

    if (!found) {
      sheet.appendRow(['biayaAdmin', targetAdmin]);
    }

    logAction('UPDATE_PENGATURAN', 'Ubah biaya admin default ke Rp ' + targetAdmin);
    return { success: true };
  } catch(e) {
    return { success: false, message: 'Kesalahan sistem: ' + e.message };
  } finally {
    lock.releaseLock();
  }
}


// ==========================================
// API TRANSAKSI
// ==========================================
function saveTransaksi(trx) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Transaksi');
    
    var newId = generateId('TRX');
    var timestamp = new Date();
    
    var rowData = [
      newId,
      timestamp,
      String(trx.nopel).trim(),
      String(trx.nama).trim(),
      String(trx.tarif).trim().toUpperCase(),
      String(trx.periode).trim().toUpperCase(),
      String(trx.stand).trim(),
      parseFloat(trx.tagihanPLN) || 0,
      parseFloat(trx.admin) || 0,
      parseFloat(trx.total) || 0
    ];

    sheet.appendRow(rowData);
    
    // Inject response payload untuk frontend
    trx.id = newId;
    trx.tanggal = timestamp.toISOString();
    
    logAction('CREATE_TRANSAKSI', 'Mencetak struk untuk NoPel: ' + trx.nopel);
    return { success: true, data: trx };
  } catch(e) {
    return { success: false, message: 'Kesalahan sistem saat menyimpan: ' + e.message };
  } finally {
    lock.releaseLock();
  }
}
